# Generated by Django 2.1.3 on 2020-02-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20200207_1009'),
        ('system_log', '0004_auto_20200207_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionchangelog',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
