# Generated by Django 2.1.3 on 2020-09-15 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_member_tc_value'),
        ('system_log', '0006_logtravelcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTravelPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issue', models.DateField(default=datetime.date.today)),
                ('statement', models.CharField(blank=True, max_length=255, null=True)),
                ('silver_in', models.IntegerField(default=0)),
                ('silver_out', models.IntegerField(default=0)),
                ('gold_in', models.IntegerField(default=0)),
                ('gold_out', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('remark', models.CharField(max_length=255)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member')),
            ],
            options={
                'verbose_name_plural': 'TravelPoint log',
            },
        ),
    ]
