# Generated by Django 2.1.1 on 2018-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('usercode', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('usertype', models.IntegerField(blank=True, null=True)),
                ('object1', models.IntegerField(blank=True, null=True)),
                ('object2', models.IntegerField(blank=True, null=True)),
                ('object3', models.IntegerField(blank=True, null=True)),
                ('object4', models.IntegerField(blank=True, null=True)),
                ('object5', models.IntegerField(blank=True, null=True)),
                ('object6', models.IntegerField()),
                ('object7', models.IntegerField()),
                ('object8', models.IntegerField()),
                ('object9', models.IntegerField()),
                ('object10', models.IntegerField()),
                ('inv_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('accessright', models.TextField(blank=True, null=True)),
                ('code_ref', models.CharField(max_length=255)),
                ('checkbackdate', models.IntegerField()),
                ('limitcredit', models.IntegerField()),
                ('mtype', models.IntegerField()),
            ],
            options={
                'db_table': 'ali_user',
            },
        ),
    ]
