# Generated by Django 2.1.1 on 2018-10-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliuser',
            options={'verbose_name_plural': 'StaffUser'},
        ),
    ]
