# Generated by Django 2.1.1 on 2018-11-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20181016_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=128)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
