# Generated by Django 2.1.3 on 2020-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_auto_20200207_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdpvstack',
            name='offset_day',
            field=models.IntegerField(default=0),
        ),
    ]
