# Generated by Django 2.1.1 on 2018-11-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_transfer_sale_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='bill_state',
            field=models.CharField(blank=True, choices=[('OR', 'ORDER'), ('PP', 'PaymentPending'), ('CA', 'Cancel'), ('CM', 'Completed'), ('PS', 'PrepareShip'), ('SH', 'Shipped')],
                                   max_length=4, null=True),

        ),
        migrations.AlterField(
            model_name='product',
            name='ato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='bf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='locationbase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='personel_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qtyr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sa_type_a',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sa_type_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sup_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='asend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ato_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ato_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='bmcauto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='bprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='caddress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='camphurid',
            field=models.CharField(blank=True, db_column='camphurId', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cancel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cdistrictid',
            field=models.CharField(blank=True, db_column='cdistrictId', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='checkportal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkcash',
            field=models.CharField(blank=True, db_column='chkCash', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkcredit1',
            field=models.CharField(blank=True, db_column='chkCredit1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkcredit2',
            field=models.CharField(blank=True, db_column='chkCredit2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkcredit3',
            field=models.CharField(blank=True, db_column='chkCredit3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkcredit4',
            field=models.CharField(blank=True, db_column='chkCredit4', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkdiscount',
            field=models.CharField(blank=True, db_column='chkDiscount', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkfuture',
            field=models.CharField(blank=True, db_column='chkFuture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkinternet',
            field=models.CharField(blank=True, db_column='chkInternet', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chkother',
            field=models.CharField(blank=True, db_column='chkOther', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='chktransfer',
            field=models.CharField(blank=True, db_column='chkTransfer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cmobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='cprovinceid',
            field=models.CharField(blank=True, db_column='cprovinceId', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='crate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='czip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='dl',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ewallet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ewallet_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ewallet_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='hcancel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='hdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='hpv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='htotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='inv_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='inv_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ipay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='lid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='locationbase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='mbase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='mcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='name_f',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='name_t',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='online',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optioncash',
            field=models.CharField(blank=True, db_column='optionCash', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optioncredit1',
            field=models.CharField(blank=True, db_column='optionCredit1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optioncredit2',
            field=models.CharField(blank=True, db_column='optionCredit2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optioncredit3',
            field=models.CharField(blank=True, db_column='optionCredit3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optioncredit4',
            field=models.CharField(blank=True, db_column='optionCredit4', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optiondiscount',
            field=models.CharField(blank=True, db_column='optionDiscount', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optionfuture',
            field=models.CharField(blank=True, db_column='optionFuture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optioninternet',
            field=models.CharField(blank=True, db_column='optionInternet', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optionother',
            field=models.CharField(blank=True, db_column='optionOther', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optiontransfer',
            field=models.CharField(blank=True, db_column='optionTransfer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optiontransfer1',
            field=models.CharField(blank=True, db_column='optionTransfer1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optiontransfer2',
            field=models.CharField(blank=True, db_column='optionTransfer2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optiontransfer3',
            field=models.CharField(blank=True, db_column='optionTransfer3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='optionvoucher',
            field=models.CharField(blank=True, db_column='optionVoucher', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='pano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='pay_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='print',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='rcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='receive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sa_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sadate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sano',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='scheck',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectcash',
            field=models.CharField(blank=True, db_column='selectCash', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectcredit1',
            field=models.CharField(blank=True, db_column='selectCredit1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectcredit2',
            field=models.CharField(blank=True, db_column='selectCredit2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectcredit3',
            field=models.CharField(blank=True, db_column='selectCredit3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectdiscount',
            field=models.CharField(blank=True, db_column='selectDiscount', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectinternet',
            field=models.CharField(blank=True, db_column='selectInternet', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selecttransfer',
            field=models.CharField(blank=True, db_column='selectTransfer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selecttransfer1',
            field=models.CharField(blank=True, db_column='selectTransfer1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selecttransfer2',
            field=models.CharField(blank=True, db_column='selectTransfer2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selecttransfer3',
            field=models.CharField(blank=True, db_column='selectTransfer3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='selectvoucher',
            field=models.CharField(blank=True, db_column='selectVoucher', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='send',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sender_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='sp_pos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='status_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_bv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_fv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_pv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_sppv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_exvat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_invat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtcash',
            field=models.DecimalField(blank=True, db_column='txtCash', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtcredit1',
            field=models.DecimalField(blank=True, db_column='txtCredit1', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtcredit2',
            field=models.DecimalField(blank=True, db_column='txtCredit2', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtcredit3',
            field=models.DecimalField(blank=True, db_column='txtCredit3', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtcredit4',
            field=models.DecimalField(blank=True, db_column='txtCredit4', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtdiscount',
            field=models.DecimalField(blank=True, db_column='txtDiscount', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtfuture',
            field=models.DecimalField(blank=True, db_column='txtFuture', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtinternet',
            field=models.DecimalField(blank=True, db_column='txtInternet', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtoption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtother',
            field=models.DecimalField(blank=True, db_column='txtOther', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtsending',
            field=models.DecimalField(blank=True, db_column='txtSending', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txttransfer',
            field=models.DecimalField(blank=True, db_column='txtTransfer', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txttransfer1',
            field=models.CharField(blank=True, db_column='txtTransfer1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txttransfer2',
            field=models.CharField(blank=True, db_column='txtTransfer2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txttransfer3',
            field=models.CharField(blank=True, db_column='txtTransfer3', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='txtvoucher',
            field=models.DecimalField(blank=True, db_column='txtVoucher', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='uid_branch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='uid_cancel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='uid_receive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='uid_sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='usercode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
