# Generated by Django 2.0.9 on 2018-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20181121_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshippromotion',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
