# Generated by Django 2.1.3 on 2018-11-26 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_saleinvoice_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promotionitem',
            options={},
        ),
    ]
