# Generated by Django 2.1.3 on 2018-11-29 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20181126_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='sctime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
