# Generated by Django 2.1.3 on 2018-12-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20181124_0132'),
        ('ecommerce', '0013_t2ppresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issue', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(default=0)),
                ('remaining', models.FloatField(default=0)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
