# Generated by Django 2.1.3 on 2018-12-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20181225_1109'),
        ('ecommerce', '0015_auto_20181218_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
