# Generated by Django 2.1.3 on 2018-12-25 04:20

from django.db import migrations
from django.db.models import Count


def link_sale_invoice(apps, schema_editor):
    SaleInvoice = apps.get_model('ecommerce', 'SaleInvoice')
    Member = apps.get_model('member', 'Member')
    allInv = SaleInvoice.objects.values('mcode').annotate(memberid=Count('mcode')).order_by('-memberid')
    pool = [i['mcode'] for i in allInv]
    member = {x.mcode: x.id for x in Member.objects.filter(mcode__in=pool)}
    for k, v in member.items():
        print('Update : {}'.format(k))
        SaleInvoice.objects.filter(mcode=k).update(member_id=v)
    return


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce', '0016_saleinvoice_member'),
    ]

    operations = [
        migrations.RunPython(link_sale_invoice),
    ]
