# Generated by Django 2.1.3 on 2019-01-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_link_invoice_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promotionitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.Promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='customer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
