# Generated by Django 2.1.3 on 2019-01-04 16:03

from django.db import migrations
from django.db.models import F


def link_sale_item(apps, schema_editor):
    PromotionItem = apps.get_model('ecommerce', 'PromotionItem')
    PromotionItem.objects.all().update(promotion=F('package'), product=F('pcode'))
    return


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce', '0019_promotionitem_product'),
    ]

    operations = [
        migrations.RunPython(link_sale_item),

    ]
