# Generated by Django 2.1.3 on 2019-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('branch', '0008_auto_20181212_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=16, db_column='mcode')),
                ('client_name', models.CharField(max_length=255, db_column='name_t')),
                ('branch_name', models.CharField(max_length=32, db_column='inv_code')),
                ('from_branch', models.CharField(max_length=32, db_column='inv_ref')),
                ('to_branch', models.CharField(max_length=32, db_column='inv_action')),
                ('bill_number', models.CharField(max_length=64, db_column='sano')),
                ('sano_ref', models.CharField(max_length=64)),
                ('pcode', models.CharField(max_length=32)),
                ('pdesc', models.CharField(max_length=255)),
                ('in_qty', models.IntegerField()),
                ('in_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('in_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('out_qty', models.IntegerField()),
                ('out_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('out_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_issue', models.DateField(auto_now_add=True, db_column='sadate')),
                ('rdate', models.DateTimeField(auto_now_add=True, db_column='rdate')),
                ('rccode', models.CharField(max_length=16)),
                ('bring_forward', models.IntegerField(db_column='yokma')),
                ('balance', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('uid', models.CharField(max_length=32)),
                ('action', models.CharField(max_length=16)),
                ('cancel', models.IntegerField()),
            ],
            options={
                'db_table': 'ali_stockcard_s',
            },
        ),
    ]
