# Generated by Django 2.1.3 on 2019-02-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0013_historicalbranchgoodsexportstatement_historicalbranchgoodsimportstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='branch',
            name='post_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='branch',
            name='sub_district',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
