# Generated by Django 2.1.3 on 2019-06-14 03:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0023_auto_20190215_1257'),
        ('accounting', '0001_initial'),
        ('branch', '0015_branch_branch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchGoodsSnapRemainingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BranchGoodsSnapRemainingStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_issue', models.DateField(default=datetime.date.today)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('discount', models.FloatField(default=0)),
                ('create_user', models.CharField(blank=True, max_length=32, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch')),
                ('statement_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StatementState')),
                ('statement_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StatementType')),
            ],
            options={
                'ordering': ('-create_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalBranchGoodsSnapRemainingStatement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_issue', models.DateField(default=datetime.date.today)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('discount', models.FloatField(default=0)),
                ('create_user', models.CharField(blank=True, max_length=32, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.Branch')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('statement_state', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.StatementState')),
                ('statement_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.StatementType')),
            ],
            options={
                'verbose_name': 'historical branch goods snap remaining statement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='branchgoodtransfer',
            options={'managed': False, 'ordering': ('id', 'sctime')},
        ),
        migrations.AddField(
            model_name='branchgoodsimportstatement',
            name='import_statement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.BranchGoodsImportStatement'),
        ),
        migrations.AddField(
            model_name='historicalbranchgoodsimportstatement',
            name='import_statement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branch.BranchGoodsImportStatement'),
        ),
        migrations.AlterField(
            model_name='branchgoodtransferitem',
            name='fv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='branchgoodtransferitem',
            name='locationbase',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branchgoodtransferitem',
            name='outstanding',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branchgoodtransferitem',
            name='uidbase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='from_branch',
            field=models.CharField(blank=True, db_column='inv_ref', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='to_branch',
            field=models.CharField(blank=True, db_column='inv_action', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='branchgoodssnapremainingitem',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branch.BranchGoodsSnapRemainingStatement'),
        ),
    ]
