# Generated by Django 2.1.1 on 2018-10-15 18:56

from django.db import migrations
from django.db.models import F


def link_sale_invoice(apps, schema_editor):
    # SaleInvoice = apps.get_model('ecommerce', 'SaleInvoice')
    # SaleItem = apps.get_model('ecommerce', 'SaleItem')
    # SaleItem.objects.all().update(sano_link_id=F('sano'))
    # for s in SaleInvoice.objects.all():
        # SaleItem.objects.filter(sano=s.id).update(sano_link=s)
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('ecommerce', '0002_saleitem_sano_link'),
    ]

    operations = [
        migrations.RunPython(link_sale_invoice),
    ]
