# Generated by Django 2.1.3 on 2018-11-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20181121_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshippromotion',
            name='ship_prices',
            field=models.CharField(default='(0,0)', max_length=32),
        ),
    ]
