# Generated by Django 2.1.3 on 2018-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_dropshippromotion_ship_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
