# Generated by Django 2.1.3 on 2018-12-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20181129_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='T2PPResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(blank=True, max_length=32)),
                ('invoice_no', models.CharField(blank=True, max_length=32)),
                ('amount', models.CharField(blank=True, max_length=32)),
                ('tx_id', models.CharField(blank=True, max_length=32)),
                ('return_code', models.CharField(blank=True, max_length=8)),
                ('channel', models.CharField(blank=True, max_length=32)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.SaleInvoice')),
            ],
        ),
    ]
