# Generated by Django 2.1.3 on 2018-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_memberdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='sadate',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_pv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='tot_bv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'ordering': ('-sadate',), 'verbose_name_plural': 'Sale Invoice'},
        ),
    ]
