# Generated by Django 2.1.3 on 2020-05-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20200313_0021'),
        ('ecommerce', '0024_auto_20200526_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default=' ', max_length=128, null=True)),
                ('mobile', models.CharField(blank=True, default=' ', max_length=128, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=128, null=True)),
                ('sub_district', models.CharField(blank=True, default=' ', max_length=64, null=True)),
                ('district', models.CharField(blank=True, default=' ', max_length=64, null=True)),
                ('province', models.CharField(blank=True, default=' ', max_length=64, null=True)),
                ('post_code', models.IntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
