# Generated by Django 2.1.3 on 2020-06-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_membershippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingbox',
            name='space_margin',
            field=models.FloatField(default=1),
        ),
    ]
