# Generated by Django 2.1.3 on 2020-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20200916_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatoship',
            name='chktc',
            field=models.CharField(blank=True, db_column='chktc', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='eatoship',
            name='optiontc',
            field=models.CharField(blank=True, db_column='optiontc', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='eatoship',
            name='selecttc',
            field=models.CharField(blank=True, db_column='selecttc', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='eatoship',
            name='txttc',
            field=models.DecimalField(blank=True, db_column='txttc', decimal_places=2, max_digits=15, null=True),
        ),
    ]
