# Generated by Django 2.1.3 on 2018-11-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181016_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='acc_no_img_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id_card_img_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
