# Generated by Django 2.1.3 on 2018-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20181124_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='exp_pos',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='exp_pos_60',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='pos_cur3_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
