# Generated by Django 2.1.3 on 2018-12-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20181124_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
    ]
