# Generated by Django 2.1.3 on 2019-01-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20181225_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='line_center',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
