# Generated by Django 2.1.3 on 2019-04-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_line_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=64)),
                ('code', models.CharField(default=' ', max_length=4)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='member',
            name='distributor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='vat_type',
            field=models.CharField(blank=True, choices=[('VT', 'VAT'), ('NV', 'NONE VAT')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='vat_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.ClientVatType'),
        ),
    ]
