# Generated by Django 2.1.3 on 2019-05-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20190424_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='favorite',
            field=models.ManyToManyField(related_name='subscribe', to='member.Member'),
        ),
    ]
