# Generated by Django 2.1.3 on 2019-08-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_member_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, choices=[('S', 'SUSPEND'), ('T', 'Terminate'), ('C', 'Change')], max_length=1, null=True)),
                ('change', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatusStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now=True, null=True)),
                ('stack_type', models.CharField(blank=True, choices=[('S', 'SUSPEND'), ('T', 'Terminate')], max_length=1, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberActive',
            fields=[
                ('member', models.CharField(blank=True, max_length=64, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'matrix_memberactive',
                'ordering': ['-last_seen'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberDocumentCheckup',
            fields=[
                ('date_issue', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('suspend', models.IntegerField(default=0)),
                ('terminate', models.IntegerField(default=0)),
            ],
        ),
    ]
