# Generated by Django 2.1.3 on 2020-01-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20191207_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=64)),
                ('code', models.CharField(default=' ', max_length=4)),
                ('note', models.TextField()),
                ('stamp_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
