# Generated by Django 2.1.3 on 2020-02-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_member_agency_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
