# Generated by Django 2.1.3 on 2020-09-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20200313_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tc_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
