from django.db import models


class WeekPayment(models.Model):
    status_pv = models.DecimalField(max_digits=15, decimal_places=2)
    week_round = models.IntegerField(db_column='rcode')
    mcode = models.CharField(max_length=255)
    member = models.ForeignKey('member.Member', on_delete=models.SET_NULL, null=True)
    paid_state = models.CharField(max_length=2, db_column='status')
    bring_forward = models.DecimalField(max_digits=15, decimal_places=2, db_column='pv')
    balance = models.DecimalField(max_digits=15, decimal_places=2, db_column='pvb')
    carry_forward = models.DecimalField(max_digits=15, decimal_places=2, db_column='pvh')
    current_amt = models.DecimalField(max_digits=15, decimal_places=2, db_column='ewallet')
    fob = models.DecimalField(max_digits=15, decimal_places=2)
    cycle = models.DecimalField(max_digits=15, decimal_places=2)
    smb = models.DecimalField(max_digits=15, decimal_places=2)
    matching = models.DecimalField(max_digits=15, decimal_places=2)
    onetime = models.DecimalField(max_digits=15, decimal_places=2)
    atoship = models.DecimalField(max_digits=15, decimal_places=2)
    ecom = models.DecimalField(max_digits=15, decimal_places=2)
    ecom_round = models.DecimalField(max_digits=15, decimal_places=2)
    ecomtranfer = models.DecimalField(max_digits=15, decimal_places=2)
    total = models.DecimalField(max_digits=15, decimal_places=2, db_column='total')
    cumulative_paid = models.DecimalField(max_digits=15, decimal_places=2, db_column='totaly')
    tot_vat = models.DecimalField(max_digits=15, decimal_places=2, db_column='tot_vat')
    tax = models.DecimalField(max_digits=15, decimal_places=2, db_column='tot_tax')
    title = models.CharField(max_length=255)
    mdate = models.DateField()
    month_pv = models.CharField(max_length=10)
    current_level = models.CharField(max_length=255, db_column='mpos')
    c_note1 = models.CharField(max_length=255)
    c_note2 = models.CharField(max_length=255)
    c_note3 = models.CharField(max_length=255)
    c_note4 = models.CharField(max_length=255)
    c_note5 = models.CharField(max_length=255)
    c_transfer = models.CharField(max_length=255)
    c_remark = models.CharField(max_length=255)
    sms_credits = models.IntegerField()
    paydate = models.CharField(max_length=255)
    locationbase = models.IntegerField()
    crate = models.DecimalField(max_digits=11, decimal_places=6)
    voucher = models.DecimalField(max_digits=15, decimal_places=2)
    mtype = models.IntegerField()
    com_transfer_chagre = models.DecimalField(max_digits=15, decimal_places=2)
    name_f = models.CharField(max_length=255)
    name_t = models.CharField(max_length=255)
    id_card = models.CharField(max_length=255)
    id_tax = models.CharField(max_length=255)
    date_start = models.DateField(db_column='fdate')
    date_issue = models.DateField(db_column='tdate')
    bankcode = models.CharField(max_length=255)

    class Meta:
        db_table = 'ali_cmbonus'


class MonthPayment(models.Model):
    status_pv = models.DecimalField(max_digits=15, decimal_places=2)
    month_round = models.IntegerField(db_column='rcode')
    date_start = models.DateField(db_column='fdate')
    date_issue = models.DateField(db_column='tdate')
    mcode = models.CharField(max_length=255)
    member = models.ForeignKey('member.Member', on_delete=models.SET_NULL, null=True)
    paid_state = models.CharField(max_length=2, db_column='status')
    bring_forward = models.DecimalField(max_digits=15, decimal_places=2, db_column='pv')
    balance = models.DecimalField(max_digits=15, decimal_places=2, db_column='pvb')
    carry_forward = models.DecimalField(max_digits=15, decimal_places=2, db_column='pvh')
    total = models.DecimalField(max_digits=15, decimal_places=2, db_column='total')
    dmbonus = models.DecimalField(max_digits=15, decimal_places=2)
    embonus = models.DecimalField(max_digits=15, decimal_places=2)
    cumulative_paid = models.DecimalField(max_digits=15, decimal_places=2, db_column='totaly')
    tot_vat = models.DecimalField(max_digits=15, decimal_places=2, db_column='tot_vat')
    tax = models.DecimalField(max_digits=15, decimal_places=2, db_column='tot_tax')
    title = models.CharField(max_length=255)
    mdate = models.DateField()
    month_pv = models.CharField(max_length=10)
    current_level = models.CharField(max_length=255, db_column='mpos')
    c_note1 = models.CharField(max_length=255)
    c_note2 = models.CharField(max_length=255)
    c_note3 = models.CharField(max_length=255)
    c_note4 = models.CharField(max_length=255)
    c_note5 = models.CharField(max_length=255)
    c_transfer = models.CharField(max_length=255)
    c_remark = models.CharField(max_length=255)
    sms_credits = models.IntegerField()
    paydate = models.CharField(max_length=255)
    locationbase = models.IntegerField()
    crate = models.DecimalField(max_digits=11, decimal_places=6)
    voucher = models.DecimalField(max_digits=15, decimal_places=2)
    mtype = models.IntegerField()
    com_transfer_chagre = models.DecimalField(max_digits=15, decimal_places=2)
    name_f = models.CharField(max_length=255)
    name_t = models.CharField(max_length=255)
    id_card = models.CharField(max_length=255)
    id_tax = models.CharField(max_length=255)
    vip = models.IntegerField()
    bankcode = models.CharField(max_length=5)
    acc_no = models.CharField(max_length=255)
    acc_name = models.CharField(max_length=250)
    branch = models.CharField(max_length=255)
    mobile = models.CharField(max_length=255)
    cmp = models.CharField(max_length=255)
    cmp2 = models.CharField(max_length=255)

    class Meta:
        db_table = 'ali_cmbonus_b'
