# Generated by Django 2.1.3 on 2018-12-11 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0005_auto_20181130_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0006_auto_20181124_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.BinaryField(blank=True, max_length=64, null=True)),
                ('current_lang', models.CharField(default='TH', max_length=4)),
                ('current_currency', models.CharField(default='BTH', max_length=4)),
                ('mirror_mode', models.BooleanField(default=False)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User account',
            },
        ),
    ]
