# Generated by Django 2.1.3 on 2019-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_preattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='preattendee',
            name='group',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
