# Generated by Django 2.1.3 on 2019-03-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_preattendee_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preattendee',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
