# Generated by Django 2.1.3 on 2019-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20190108_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripapplication',
            name='previous_use',
            field=models.IntegerField(default=0),
        ),
    ]
