# Generated by Django 2.1.3 on 2020-07-31 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20200313_0021'),
        ('trip', '0003_tripapplication_previous_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPointStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_date', models.DateField(default=datetime.date.today)),
                ('gold_point', models.IntegerField(default=0)),
                ('silver_point', models.IntegerField(default=0)),
                ('remaining_gold_point', models.IntegerField(default=0)),
                ('remaining_silver_point', models.IntegerField(default=0)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ('stamp_date',),
            },
        ),
        migrations.CreateModel(
            name='TravelPointUseStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=32, null=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('gold_coin', models.IntegerField(default=0)),
                ('silver_coin', models.IntegerField(default=0)),
                ('state', models.CharField(blank=True, choices=[('CA', 'Cancel'), ('CM', 'Completed')], max_length=2, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'ordering': ('-issue_date',),
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='minimum_matching',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='required_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='required_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travelpointusestatement',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.Trip'),
        ),
    ]
