# Generated by Django 2.1.3 on 2018-12-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0006_auto_20181124_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('register_period', models.DateField()),
                ('balance', models.IntegerField(blank=True, default=0)),
                ('month_qualified', models.IntegerField(blank=True, default=0)),
                ('condition', models.TextField(blank=True)),
                ('max_seat', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Travel Event',
            },
        ),
        migrations.CreateModel(
            name='TripApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateField(auto_now_add=True)),
                ('balance_use', models.IntegerField(default=0)),
                ('seat', models.IntegerField(default=0)),
                ('member', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_enter', to='member.Member')),
                ('trip', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='trip.Trip')),
            ],
            options={
                'ordering': ('-trip__start',),
            },
        ),
    ]
