# Generated by Django 2.1.3 on 2018-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20181124_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='suspend_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='terminate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
