# Generated by Django 2.1.3 on 2019-12-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_memberlogs_memberstatusstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sponsor_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sponsor_lft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sponsor_rgt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
