# Generated by Django 2.1.3 on 2020-01-29 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='agency_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_child', to='member.Member'),
        ),
    ]
