# Generated by Django 2.1.3 on 2020-03-12 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20200207_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='stamp_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
