# Generated by Django 2.1.1 on 2018-11-03 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtransfer',
            name='remote_ip',
            field=models.CharField(blank=True, default='localhost', max_length=64),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='bmcauto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='bprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='crate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='hono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='inv_code_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='locationbase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='mbase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='name_f',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='name_t',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='print',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='rcode',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='sano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='sp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='sp_pos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='status_package',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='tot_fv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='tot_sppv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='trnf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvtransfer',
            name='uid_cancel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
