# Generated by Django 2.1.3 on 2019-04-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_line_center'),
        ('commission', '0004_auto_20190103_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthpayment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
        migrations.AddField(
            model_name='weekpayment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Member'),
        ),
    ]
