# Generated by Django 2.1.3 on 2019-12-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20191207_2200'),
        ('commission', '0005_auto_20190402_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtransfer',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_outs', to='member.Member'),
        ),
    ]
