# Generated by Django 2.1.3 on 2020-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_holdpvstack_offset_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdpvstack',
            name='stack_type',
            field=models.CharField(blank=True, choices=[('S', 'Sale'), ('T', 'Transfer')], default='S', max_length=4, null=True),
        ),
    ]
