from .eautochip import LogEautoshipAdmin
from .ewallet import LogEwalletAdmin
from .hpv import LogHpvAdmin
from .log import LogAdmin
from .voucher import LogVoucherAdmin
from .wallet import LogWalletAdmin
from .position_change_log import PositionChangeLogAdmin
from .travel_credit import LogTravelCreditAdmin
from .travel_point import LogTravelPointAdmin
