# Generated by Django 2.1.3 on 2019-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcode', models.IntegerField()),
                ('mcode', models.CharField(max_length=20)),
                ('pos_before', models.CharField(blank=True, max_length=11, null=True)),
                ('pos_after', models.CharField(blank=True, max_length=11, null=True)),
                ('date_change', models.DateField(blank=True, null=True)),
                ('date_update', models.DateField()),
                ('type', models.CharField(max_length=255)),
                ('up_down', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ali_calc_poschange',
                'managed': False,
            },
        ),
    ]
