# Generated by Django 2.1.3 on 2019-08-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_log', '0002_positionchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loghpv',
            name='bring_forward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
