# Generated by Django 2.1.3 on 2018-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20181130_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjuststatement',
            name='usercode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
