# Generated by Django 2.1.3 on 2018-12-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('branch', '0005_auto_20181130_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='branch.Branch'),
        ),
    ]
