# Generated by Django 2.1.3 on 2019-01-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0009_stockstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockstatement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='balance',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='cancel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='in_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='in_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='in_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='out_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='out_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='out_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='rccode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='bring_forward',
            field=models.IntegerField(blank=True, db_column='yokma', null=True),
        ),
        migrations.AlterModelOptions(
            name='stockstatement',
            options={'ordering': ('-id',)},
        ),

    ]
