# Generated by Django 2.1.3 on 2019-02-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0010_auto_20190124_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bewallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='branch',
            name='bvoucher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='branch',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ewallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='branch',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='inv_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='locationbase',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='branch',
            name='no_tax',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='voucher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='qtyd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='qtyr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='qtys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='branchstock',
            name='ud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockstatement',
            name='sano_ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
