# Generated by Django 2.1.3 on 2019-02-19 15:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('ecommerce', '0023_auto_20190215_1257'),
        ('branch', '0011_auto_20190215_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchGoodsExportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BranchGoodsExportStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_issue', models.DateField(default=datetime.date.today)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('discount', models.FloatField(default=0)),
                ('create_user', models.CharField(blank=True, max_length=32, null=True)),
                ('seller_name', models.CharField(max_length=128)),
                ('total', models.FloatField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch')),
                ('statement_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StatementState')),
                ('statement_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StatementType')),
                ('to_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_statements', to='branch.Branch')),
            ],
            options={
                'ordering': ('-create_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BranchGoodsImportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BranchGoodsImportStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=32)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_issue', models.DateField(default=datetime.date.today)),
                ('remark', models.CharField(blank=True, max_length=128, null=True)),
                ('discount', models.FloatField(default=0)),
                ('create_user', models.CharField(blank=True, max_length=32, null=True)),
                ('seller_name', models.CharField(max_length=128)),
                ('total', models.FloatField(default=0)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Branch')),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_statements', to='branch.Branch')),
                ('statement_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StatementState')),
                ('statement_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.StatementType')),
            ],
            options={
                'ordering': ('-create_date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='branchgoodsimportitem',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branch.BranchGoodsImportStatement'),
        ),
        migrations.AddField(
            model_name='branchgoodsexportitem',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='branch.BranchGoodsExportStatement'),
        ),
    ]
